### ISSUE TITLE
Does the landsat-qa-arcgis-toolbox require update to support Landsat Collection 1 Level-1 QA data?

### ISSUE THREAD

**Issue by sadareen** [USGS-EROS/landsat-qa-arcgis-toolbox#1]
Hi, 

I recently used the landsat-qa-arcgis-toolbox to unpack a Landsat QA Band (Scene ID: LC81690582016079LGN00_BQA.tif) in ArcMap. While running the tool, I received an error. I probably think the landsat-qa-arcgis-toolbox needs to be updated to support Collection 1 Level-1 QA data. Although I can find Landsat QA Tools here https://landsat.usgs.gov/landsat-qa-tools which includes Windows 64-bit executables, I find it easier to use the ArcGIS toolbox. I would be grateful if someone can suggest how to incorporate the new/updated band values into the landsat-qa-arcgis-toolbox. I am completely new to python programming. Following text (font in italics) is a part of the error message that I received while running the toolbox.  

_ERROR: Band value 20480 in file E:\landsat-qa-arcgis-toolbox-master\LC81690582016079LGN00_BQA.TIF does not have a corresponding key value for BQA band.
.
.
.
ERROR: Band value 61440 in file E:\landsat-qa-arcgis-toolbox-master\LC81690582016079LGN00_BQA.TIF does not have a corresponding key value for BQA band.
Completed script DecodeQA...
Failed to execute (DecodeQA)._

Thanks,
james

**Comment by stevefoga** [comment]
Hello,

The ArcGIS tool actually _only_ supports Landsat Collection 1 (C1) BQA bands. The product you are using is "pre-collection" data, which is being discontinued in the USGS archive beginning in October. You can tell the difference between pre-collection and C1 products because their IDs are different; see https://landsat.usgs.gov/landsat-collections#Prod IDs for more details.

I would suggest you download your product again from EarthExplorer. Collection 1 data is found under the "Data Sets" > "Landsat Archive" > "Collection 1 Level-1" tabs.

> Although I can find Landsat QA Tools here https://landsat.usgs.gov/landsat-qa-tools which includes Windows 64-bit executables, I find it easier to use the ArcGIS toolbox.
I'll note that at this time, the ArcGIS Toolbox only generates an attribute table and names each unique category. The "landsat-qa-tools" executables actually generate discrete bands for each category (e.g., "*_clouds.tif", "*_shadow.tif", etc.) We hope to eventually add the unpacking functionality into the ArcGIS Toolbox.

**Comment by sadareen** [comment]
Steve, thank you so much for your immediate and helpful reply.
This was my mistake. I should have double checked the Product ID before posting. This is the C1 Scene ID LC08_L1TP_169058_20160319_20170328_01_T1. I usually use USGS EE to download Landsat level 1 data but due to limitations in data usage from my ISP, I was looking for an alternative website to download only the BQA Band from the same scene instead of the bundled 11 bands of Landsat 8 which is approx. 1GB. I found a website https://lv.eosda.com/ to download the individual QA band, however as you pointed out correctly it is part of the 'Pre-Collection'. Are you aware of any website where I can download the individual BQA band from Collection 1. EE unfortunately does not provide that option. One of my aims is to figure out if it is possible to isolate the 'water' pixels in a Landsat Scene using the BQA band or the 'pixel_qa' bands. I am aware of other ways such as using band combinations and water indices for the said purpose. However, I want to see if the quality bands can be of any help. It was kind of confusing initially because there are like multiple levels of quality information options: the QB, the BQA and the pixel_qa etc., until I found clarification in the USGS website.

**Comment by stevefoga** [comment]
Glad to hear it!

You are correct that EE does not currently support ordering individual bands. If you did find the documentation on the current QA bands, you'll note 'BQA' does not have a water classification, but 'pixel_qa' does. This is because we decided to leave water flagging as a 'higher level' product. 

I cannot speak officially (or accurately) for any third-party data providers, but one option for obtaining the 'pixel_qa' band is ordering it from the EROS Science Processing Architecture (ESPA; https://espa.cr.usgs.gov/). You can log in with your EE credentials. To place an order, go to 'New Order', and load in a product ID list (in a text file) and order just the 'pixel_qa' band by selecting 'Pixel QA' in the interface. This should reduce the total data volume for your orders. 

ESPA also has a [user guide](https://landsat.usgs.gov/sites/default/files/documents/espa_odi_userguide.pdf), if you're interested in any other features.

**Comment by sadareen** [comment]
Great idea Steve. Thanks for the ESPA option. I'll do that.
